fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.3.2'
    'apt':
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '1.8.0'
  symlinks:
    dariahshibboleth: "#{source_dir}"
